version: "3.9"

services:
  db1:
    image: postgres:13.4-buster
    container_name: rpg-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - rpg-db-data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - rpg-network

volumes:
  rpg-db-data:
    name: rpg-db-data

networks:
   rpg-network:
    name:  rpg-network
