name: Testing rpg_api

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Install deps
        run: |
          cd database/rpg_api
          # your dependencies installation steps here, for example:
          poetry install
      - name: Run black check
        run: |
          cd database/rpg_api
          poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Install deps
        run: |
          cd database/rpg_api
          # your dependencies installation steps here, for example:
          poetry install
      - name: Run flake8 check
        run: |
          cd database/rpg_api
          poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Install deps
        run: |
          cd database/rpg_api
          # your dependencies installation steps here, for example:
          poetry install
      - name: Run mypy check
        run: |
          cd database/rpg_api
          poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    services:
      rpg_api-db:
        image: postgres:13.8-bullseye
        env:
          POSTGRES_PASSWORD: rpg_api
          POSTGRES_USER: rpg_api
          POSTGRES_DB: rpg_api
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5435:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Install deps
        run: |
          cd database/rpg_api
          # your dependencies installation steps here, for example:
          poetry install
      - name: Run pytest check what
        run: |
          cd database/rpg_api
          poetry run pytest -vv --cov="rpg_api" .
        env:
          RPG_API_HOST: "0.0.0.0"
          RPG_API_DB_HOST: localhost
